# Numpy Exercises

## Array Creation

In [2]:
# Import Numpy package
import numpy as np

In [4]:
# Create array of 10 zeros
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Create array with values ranging from 10 to 49
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
# Create 2x2 matrix filled with 1s
b = np.array([[1,1],[1,1]])
# OR
c = np.ones([2,2], dtype=int)

In [23]:
# Create a 3x2 matrix filled with 1s as floats
d = np.ones([3,2], dtype=float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=int)
e = np.ones_like(X)
e

array([1, 1, 1, 1])

In [27]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with zeros.
f = np.zeros_like(X)
f

array([0, 0, 0, 0])

In [29]:
# Create a numpy matrix of 4*4 integers, filled with fives.
g = np.ones([4,4], dtype=int) * 5
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with zeros.
h = np.ones_like(X) * 7
h

array([7, 7, 7, 7])

In [39]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
j = np.random.randint(1,10,3)
j

array([9, 2, 2])

In [47]:
k = np.random.rand(3,3,3)
k

array([[[0.61079092, 0.87650571, 0.66577488],
        [0.15831474, 0.24235565, 0.27003706],
        [0.16694358, 0.0896105 , 0.3821746 ]],

       [[0.94134723, 0.96835622, 0.50759013],
        [0.50141811, 0.51600102, 0.47743753],
        [0.36673671, 0.77476021, 0.88465335]],

       [[0.98944104, 0.90138248, 0.96709896],
        [0.01616787, 0.16833694, 0.79955273],
        [0.57610825, 0.06837978, 0.21416318]]])

In [50]:
# Given the X python list convert it to an Y numpy array
l = [1,3,5]
m = np.array(l)
m

array([1, 3, 5])

In [55]:
# Given the X numpy array, make a copy and store it on Y.
n = np.copy(m)
n

array([1, 3, 5])

In [56]:
# Create a numpy array with numbers from 1 to 10
o = np.arange(1,11)
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# Create a numpy array with the odd numbers between 1 to 10
p = np.arange(1,11,2)
p

array([1, 3, 5, 7, 9])

In [63]:
# Create a numpy array with numbers from 1 to 10, in descending order.
q = np.arange(1,11)[::-1]
q

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
r = np.arange(9).reshape(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## Array Indexation