# Numpy Exercises

## Array Creation

In [2]:
# Import Numpy package
import numpy as np

In [4]:
# Create array of 10 zeros
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Create array with values ranging from 10 to 49
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
# Create 2x2 matrix filled with 1s
b = np.array([[1,1],[1,1]])
# OR
c = np.ones([2,2], dtype=int)

In [23]:
# Create a 3x2 matrix filled with 1s as floats
d = np.ones([3,2], dtype=float)
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.
X = np.arange(4, dtype=int)
e = np.ones_like(X)
e

array([1, 1, 1, 1])

In [27]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with zeros.
f = np.zeros_like(X)
f

array([0, 0, 0, 0])

In [29]:
# Create a numpy matrix of 4*4 integers, filled with fives.
g = np.ones([4,4], dtype=int) * 5
g

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with zeros.
h = np.ones_like(X) * 7
h

array([7, 7, 7, 7])

In [39]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# Create a numpy array, filled with 3 random integer values between 1 and 10.
j = np.random.randint(1,10,3)
j

array([9, 2, 2])

In [47]:
k = np.random.rand(3,3,3)
k

array([[[0.61079092, 0.87650571, 0.66577488],
        [0.15831474, 0.24235565, 0.27003706],
        [0.16694358, 0.0896105 , 0.3821746 ]],

       [[0.94134723, 0.96835622, 0.50759013],
        [0.50141811, 0.51600102, 0.47743753],
        [0.36673671, 0.77476021, 0.88465335]],

       [[0.98944104, 0.90138248, 0.96709896],
        [0.01616787, 0.16833694, 0.79955273],
        [0.57610825, 0.06837978, 0.21416318]]])

In [50]:
# Given the X python list convert it to an Y numpy array
l = [1,3,5]
m = np.array(l)
m

array([1, 3, 5])

In [55]:
# Given the X numpy array, make a copy and store it on Y.
n = np.copy(m)
n

array([1, 3, 5])

In [56]:
# Create a numpy array with numbers from 1 to 10
o = np.arange(1,11)
o

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
# Create a numpy array with the odd numbers between 1 to 10
p = np.arange(1,11,2)
p

array([1, 3, 5, 7, 9])

In [63]:
# Create a numpy array with numbers from 1 to 10, in descending order.
q = np.arange(1,11)[::-1]
q

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [66]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8
r = np.arange(9).reshape(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
# Show the memory size of the given Z numpy matrix
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## Array Indexation

In [2]:
import numpy as np
# Establish X array
X = np.array(['A','B','C','D','E'])

In [4]:
# Index the first value of X
X[0]

'A'

In [7]:
# Index the last value of X
X[-1]

'E'

In [9]:
# Index first 3 values of X
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

In [10]:
# Index middle 3 values of X
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [12]:
# Show all X values in descnding order
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [14]:
# Show all values of X in an odd position
X[0::2]

array(['A', 'C', 'E'], dtype='<U1')

In [15]:
# Establish Y array
Y = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

In [16]:
# Index first row of Y
Y[0]

array([1, 2, 3, 4])

In [19]:
# Show the last row of Y
Y[-1]

array([13, 14, 15, 16])

In [23]:
# Show the first element in the first row of Y
Y[0,0]

1

In [24]:
# Show the last elemnent in the last row of Y
Y[-1,-1]

16

In [25]:
# Show the first two elements in the first two rows of Y
Y[0:2, 0:2]

array([[1, 2],
       [5, 6]])

In [26]:
# Show the first two elements in the first two rows of Y
Y[2:4, 2:4]

array([[11, 12],
       [15, 16]])

## Array Manipulation

In [29]:
# Convert Z into a numpy float array
Z = [-5, -3, 0, 10, 40]
np.array(Z, np.float16)

array([-5., -3.,  0., 10., 40.], dtype=float16)

In [30]:
# Reorder Z to reverse order
Z[::-1]

[40, 10, 0, -3, -5]

In [32]:
# Sort Z
Z.sort()
Z

[-5, -3, 0, 10, 40]

In [34]:
# Set the 5th element equal to 1
Z[4] = 1
Z

[-5, -3, 0, 10, 1]

In [39]:
# Given Y array, change all last row values to 1
Y = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
Y[-1] = np.ones(len(Y[-1]))
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [41]:
# Add 5 to every element in Y
Y + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 6,  6,  6,  6]])

## Boolean Arrays

### Also called "masks"

In [43]:
# Given the W array, make a mask showing negative elements
W = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = W < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [46]:
# Show the negative values of W
W[mask]

array([-1, -4, -9])

In [47]:
# Show numbers higher than 5
mask5 = W > 5
W[mask5]

array([ 6, 10])

In [48]:
# Show numbers higher than the elements' mean
avg = np.mean(W)
maskAvg = W > avg
W[maskAvg]

array([ 2,  5,  6, 10])

In [51]:
# Show numbers equal to 2 or 10
mask = (W == 2) | (W == 10)
W[mask]

array([ 2, 10])

## Logic Functions

In [56]:
# Given the W numpy array, return True if none of its elements is zero
W.all()

False

In [60]:
# Given the W numpy array, return True if none of its elements is zero
W.any()

True

## Summary Statistics

In [58]:
# Given R numpy array, return the sum of the elements
R = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
R.sum()

43

In [59]:
# Return mean of R
R.mean()

4.777777777777778

In [63]:
# Given Y matrix, show the sum of its columns
Y = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
# "axis=0" equals columns; "axis=1" equals rows
Y.sum(axis=0)

array([28, 32, 36, 40])

In [65]:
# Given Y matrix, show the sum of its columns
Y.sum(axis=1)

array([10, 26, 42, 58])

In [66]:
# Show the max value of R
R.max()

9